# Generated by Django 4.2.16 on 2024-12-14 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_author_alter_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='exp_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
