# Generated by Django 4.2.16 on 2024-12-16 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_question_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, help_text='Введите описание', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='short_description',
            field=models.CharField(blank=True, help_text='Введите короткое описание', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для вопроса', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(help_text='Введите вопрос', max_length=200),
        ),
    ]
